# Configuração de Painel para Zabbix
panelIdPreamble: "zabbix-panel-"
panels:
  TUPI:
    dataSource: "ZABBIX"
    group: "VPNs_Unidades"
    item: "ICMP ping"
    label:
      separator: "colon"
      units: "ms" # Milissegundos
      decimalPoints: 2
    labelColor:
      gradientMode: "hue"
      thresholds:
        - {color: "green", level: 0}   # Tudo OK
        - {color: "red", level: 1}    # Alerta
    link:
      url: "https://www.zabbix.com/"
      params: "monitoring"
