# Panel Config

cellIdPreamble: "cell-"
cells: 
  drawio:
    link:
      url: "https://app.diagrams.net/?p=svgdata"
   

  TUPI:
    color:
    mode: 'value'
    thresholds:
        - value: 0
            color: 'green'
        - value: 1
            color: 'red'
