#------------------------------------------------------------------------------
# Configuração Flow Panel - Monitoramento ICMP Ping
# Fonte de Dados: Zabbix
#------------------------------------------------------------------------------

apiVersion: 1

cells:
  icmp-monitor:
    dataRef: "zabbix.icmpping"  # Item key padrão do Zabbix para ping
    label:
      text: "TUPI"
      separator: "none"
      units: "status"
      decimalPoints: 0
    labelColor:
      staticColor: "#000000"  # Cor do texto fixa
    fillColor:
      gradientMode: "discrete"
      thresholds:
        - {color: "#4CAF50", level: 1}  # Up
        - {color: "#F44336", level: 0}  # Down
    geometry:
      width: 120
      height: 60
      x: 520
      y: 380
    border:
      width: 1
      color: "#000000"
    link:
      url: "/d/zabbix-dashboard/zabbix-host-overview"
      params: "?var-host=${HOST}"
